FlashCardsPresentation/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FlashCardsPresentation.Models
{
    public class LoginViewModel
    {
        [Required(AllowEmptyStrings = false)]
        [EmailAddress]
        [Display(Name = "Adresse e-mail")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

FlashCardsPresentation/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FlashCards.Application;
using FlashCardsPresentation.Models;
using Microsoft.AspNetCore.Mvc;

namespace FlashCardsPresentation.Controllers
{
    public class AccountController : Controller
    {
        IAccountServices _userServices;
        public AccountController(IAccountServices userServices)
        {
            _userServices = userServices;
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(LoginViewModel loginViewModel, string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userdto = _userServices.Validate(loginViewModel.Email, loginViewModel.Password);
                    if (userdto != null)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    ModelState.AddModelError("LogInError", "e-mail ou mot de passe incorect");
                    return View();
                }
                catch (System.Exception)
                {
                    ModelState.AddModelError("LogInError", "e-mail ou mot de passe incorrect");
                    return View();
                }
            }
            else
            {
                return View();
            }
        }
    }
}

FlashCardsPresentation/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace FlashCardsPresentation.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FlashCardsPresentation/Controllers/StudyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace FlashCardsPresentation.Controllers
{
    public class StudyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Unit()
        {
            return View();
        }
    }
}

FlashCardsPresentation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>
    <a asp-area="" asp-controller="Study" asp-action="Index">>Réviser</a>
</h2>
    <h2>>Créer</h2>
    <h2>>Importer</h2>

FlashCardsPresentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/boostrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <header class="container-fluid">
            <span>FlashCards</span>
            <span class="fa fa-user fa-lg" id="account-header">AccountPlaceholder</span>
    </header>

    <div>
        @RenderBody()
    </div>
    
    <footer class="footer">FooterPlaceholder</footer>
</body>
</html>

FlashCardsPresentation/Views/Study/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>
    <a asp-action="Unit">Unit 12</a>
</h2>

FlashCardsPresentation/Views/Study/Unit.cshtml
@{
    ViewData["Title"] = "Unit";
}

<div class="flip-container" onclick="this.classList.toggle('flip')">
    <div class="flipper">
        <div class="front">
            <img src="~/img/FlashCard.jpg" />
            <div class="text-card">FRONT</div>
        </div>
        <div class="back">
            <img src="~/img/FlashCard.jpg" />
            <div class="text-card">BACK</div>
        </div>
        </div>
    </div>